<BolosScreen@MDScreen>:
    name: "bolos_screen"
    ScrollView:
        ListaReceitas:
            id: caixa_receitas

<DocesScreen@MDScreen>:
    name: "doces_screen"
    ScrollView:
        ListaReceitas:
            id: caixa_receitas

<PaesScreen@MDScreen>:
    name: "paes_screen"
    ScrollView:
        ListaReceitas:
            id: caixa_receitas

<SalgadosScreen@MDScreen>:
    name: 'salgados_screen'
    ScrollView:
        ListaReceitas:
            id: caixa_receitas
